### PR TITLE
Add workaround to support Boost 1.62

### PR DESCRIPTION
**Pull request by netspiri**
As stated in issue #158, Boost Test shipped with Boost 1.62 has some issues related to the `--log_sink` and `--report_sink` command line arguments.

This fix provides a workaround for using the test adapter with this release. By enabling the workaround via configuration:

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>

	<!-- Adapter Specific sections -->

	<!-- BoostTest adapter -->
	<BoostTest>
        	<UseBoost162Workaround>true</UseBoost162Workaround>
	</BoostTest>

</RunSettings>
```

the test adapter will try an alternative strategy at running tests. It bypasses the use of `--log_sink` via the use of `BOOST_TEST_LOGGER` environment variable (i.e. the new `--logger` command line argument) and by extracting the report output from standard error.

The proposed workaround is slower than regular execution, but this is solely limited to Boost 1.62 users. As @raffienficiaud, mentioned, a fix is in the works so this should solely be isolated to this specific release.

Documentation is available at: https://github.com/netspiri/vs-boost-unit-test-adapter/wiki/faq. Wiki will be merged upon request.

Thanks go in order to:
- @sergegers for actually identifying the issue
- @raffienficiaud for his suggestion for using `--logger`

### CODE REVIEW

**Comment by sergegers** [comment]
Thank you @netspiri . Now it's working on 1.62. Also you didn't mention to add a switch
<ForceListContent>true</ForceListContent> to adapter settings file (or it's a bug).

**Comment by netspiri** [comment]
Hi @sergegers and many thanks for the prompt feedback.

Regarding the configuration element `<ForceListContent>true</ForceListContent>`, that should be used on a case-by-case basis. If you [dynamically link to Boost Test](http://www.boost.org/doc/libs/1_62_0/libs/test/doc/html/boost_test/usage_variants.html#boost_test.usage_variants.shared_lib), then yes it is necessary. If you use other means of [compilation](http://www.boost.org/doc/libs/1_62_0/libs/test/doc/html/boost_test/usage_variants.html), then I am afraid it might be a bug (possibly related to #162). Could you kindly clarify your use case please so that we may better tackle the issue?

**Comment by sergegers** [comment]
@netspiri I'm using a static linking and it looks like exactly as #162 case.

**Comment by netspiri** [comment]
@sergegers If the force list content issue persists, kindly open a different issue and elaborate on it further there. This could also be caused by compiler/linker options but I cannot determine the root cause with the currently available information.

**Comment by sergegers** [comment]
@netspiri Ok, later I'll try create minimal test project where the bug is reproduced.

**Pull request merged**
