### PR TITLE
Add AppVeyor CI

### PR DESCRIPTION
**Pull request by netspiri**
Added AppVeyor configuration to repository along with build status badge as requested.

In brief, the build procedure attempts to:
- Update Visual Studio 2012 in case Update 3 is not installed
- Update VSIX version number to reflect AppVeyor's build number
- Build all projects (both Debug and Release configurations) along with static analysis
- Execute tests
- Expose VSIX installer as an artifact

Please note that the version number increments now need to be specified in ``appveyor.yml`` and ``source.extension.vsixmanifest``.

### CODE REVIEW

**Comment by guwirth** [comment]
Have to change link to my user because only I'm allowed to set read access for AppVeyor on repository.

* @netspiri maybe you can try a rebase and PR to see if build is visible for PR.
* build for master brunch is failing?

**Comment by guwirth** [comment]
@netspiri saw also this in the script. Can we move this to https://github.com/etas/vs-boost-unit-test-adapter/ repositpry?
```
# Download and execute madskristensen AppVeyor VSIX ExtensionScripts in order to update revision number before project build
  - ps: (New-Object System.Net.WebClient).DownloadString("https://raw.githubusercontent.com/netspiri/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
```

**Comment by netspiri** [comment]
Build failure noted but unfortunately we cannot reproduce it on our end. We are tracking the etas fork using our AppVeyor account and did manage to build it. Refer to [build log](https://ci.appveyor.com/project/netspiri/vs-boost-unit-test-adapter-du7c4/build/1.0.5.1/job/d8kn9s5m541y6yqe) and status badge on [Readme](https://github.com/netspiri/vs-boost-unit-test-adapter/blob/feature/%2330-AppVeyor-Build/README.md).

Please note that we cannot track pull requests posted on the etas fork since this requires the repository owner to set up a GitHub webhook which is automatically done when registering an AppVeyor project using a GitHub account.

The issue seems to stem from missing Visual Studio 2012 dependencies. Although Update 3 patch was stated to be successful, the time taken to install it is far less (approx. 10 seconds) than our recorded times (approx. 11 minutes).

**Comment by netspiri** [comment]
Regarding the version script, we avoided copying the script into our repository to maintain the original authors' commit history. We forked [madskristensen ExtensionScripts repository](https://github.com/madskristensen/ExtensionScripts) and simply linked to the forked content.

**Comment by netspiri** [comment]
Primary documentation regarding AppVeyor is [available](https://github.com/netspiri/vs-boost-unit-test-adapter/wiki/Continuous-Integration-AppVeyor). Should provide further help in identifying any possible issues.

**Pull request merged**
