### PR TITLE
Add '--list_content=DOT' Discovery

### LINKED ISSUE #23: Support BOOST_DATA_TEST_CASE
Support new 1.59 keyword *BOOST_DATA_TEST_CASE*: Declares and registers a data-driven test case, using a particular dataset. See http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/utf_reference/test_org_reference/test_org_boost_test_dataset.html

### LINKED ISSUE #24: Use run-time parameter list_content to get unit test names
Starting with 1.59 there is the command line parameter --list_content: This argument instructs the test runner to print out an indented listing of all test suites and test cases registered with the test runner without running the tests.

* In case the unit tests are compiled and linked the run-time parameter --list_content could be used to get the unit test names instead of parsing the sources.
* This should be an alternative approach only because not all users have already 1.59.

Proposed sequence:
```
verify if test EXE is already there:
   if yes try with  --list_content:
      if run-time parameter is supported use this list
      else parse sources 
   else parse sources
```

### LINKED ISSUE #53: Performance test V1.0.6 beta: using list_content not faster
Did a first performance test of V1.0.6 with a big solution. The current version is slightly slower. Wondering because after closing #24 and #26 it should be faster now. For testing we were using the solution HWAccessBoostTests.sln.

### LINKED ISSUE #64: Support of Boost 1.59 test decorators as additional traits ?
Hi,
we like to use the new “decorators” to organize our boost test suite in the same way as it can be done with NUnit category attributes.
http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/tests_organization/decorators.html

For that purpose it is necessary that the adapter transfers all "decorations" additionally to the "test suite" as  "visual studio test explorer trait" to visual studio (like NUnit: it transfers every category as trait). Thus a boost test method like "BOOST_AUTO_TEST_CASE(test_case2 ..." may be assigned to several traits.

For the example below  from the boost documentation we would need >= 3 traits in the visual studio test explorer:
Trait1: utf_label_trivial
Trait2: utf_label_cmp
Trait3: TestSuite_ExampleSuite
(Trait3 is already created by the Boost 1.55 Version of the “Boost Unit Test Adapter”)

Boost Docu Example
http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/tests_organization/decorators.html
BOOST_AUTO_TEST_SUITE(ExampleSuite)
BOOST_AUTO_TEST_CASE(test_case2,
  * utf::label("trivial")
  * utf::label("cmp")
  * utf::description("testing equality of ones"))
{

You can also contact me via "martin.schwienbacher@etas.com"

Mit freundlichen Grüßen / Best regards,
Martin Schwienbacher

ETAS GmbH
Engineering Software (ETAS/ESW1)
Borsigstrasse 14
70469 Stuttgart
Germany
www.etas.com

Phone +49(711)3423-2636
martin.schwienbacher@etas.com

Managing Directors: Friedhelm Pickhard, Bernd Hergert, Christopher White
Chairman of the Supervisory Board: Dr. Walter Schirm
Registered Office: Stuttgart; Registration Court: Amtsgericht Stuttgart HRB 19033

### LINKED ISSUE #88: Side effect of executing all executables after a successful build
I noticed that the te.processhost.managed.exe executes all executables that are built by projects in the solution with the command line option "--help" after each successful build. This can lead to side effects depending on what those executables do.
Example:
Imagine what happens if I build a project that creates an .exe which has the purpose to format all hard disks.

### LINKED ISSUE #93: support --list_content=DOT
From @netspiri

Recently we took some time to look into possible utilities/libraries regarding parsing DOT files. There are many alternatives available, but most of them have a dependency on GraphViz, which we would like to avoid, or have a focus on visualising DOT files.

We came across this project: http://graphviz4net.codeplex.com/. We have not experimented with it yet but it’s .core module contains a DOT parser which might be useful for our cause. Skimming the directory structure seems to show that it was generated using ANTLR (to which the grammar should be available here: http://www.antlr3.org/grammar/1138116546902/dot/). Before prototyping, we would like to know if we are allowed to use parts of this project based on its license. The project uses the LGPL license. The other alternative would be to generate the parser from the grammar directly using ANTLR.

Looking forward to hearing your thoughts regarding this.

### PR DESCRIPTION
**Pull request by netspiri**
- The current list content discovery mechanism has been overhauled to use the `--list_content=DOT`. This makes use of a DOT parser generated from the BSD licensed [DOT grammar](https://github.com/antlr/grammars-v4/tree/master/dot) provided by the ANTLR maintainers. Closes #93. Closes #24.
- Adhoc testing shows that the new mechanism is as fast as the current _SourceCodeDiscoverer_. Closes #53.
- Via the DOT representation, labels are now available as traits (refer to attached screenshot). Closes #64.  
labeltrait
- `BOOST_DATA_TEST_CASE` tests are now implicitly discovered via the new _ListContentDiscoverer_. Closes #23.
- Debug symbols are used to determine if an executable is a Boost Test executable. In case this symbol is not available due to dynamic linking with Boost Test, a new configuration element `<ForceListContent>` has been added to force the use of list content discovery. Recommended that this setting is used in conjunction with the filter setting introduced in PR #108. Closes #88.

Additionally:
- Test execution via `vstest.console.exe` is now possible with list content discovery since there is no dependency over Visual Studio. Using the new build the following is possible: `vstest.console.exe /UseVsixExtensions:true boost.test.exe`. This also implies that the adapter _may_ be used in TFS continuous integration environments.
- _ListContentDiscoverer_ is also available for external test discovery. If the `DiscoveryCommandLine` or `DiscoveryFileMap` configuration elements are missing, discovery is performed via _ListContentDiscoverer_. Note that this implies force using `--list_content=DOT` so the previous recommendation still applies.
- VSIX package has been reduced in size due to some rogue `Copy Local` references.
- Due to a conflict in design between PR #61 and PR #108, external test runner extension type regular expression patterns are now limited to the file extension only and not on the full path of the test source.
- A general refactoring exercise has been affected.
- Licenses for 3rd party components have been added to the repository and the VSIX package.
- We could not replicate issue #69 on our environments. May require further analysis.

### CODE REVIEW

**Comment by daniel-kun** [comment]
With these great new possibilities, what is the recommended way to limit test case discovery to one specific test.exe only? (for speed reasons and because the other tests shall not be used with the vs test explorer)

**Comment by guwirth** [comment]
Thanks a lot. We will do some testing...

**Comment by netspiri** [comment]
@daniel-kun The XML `.runsettings` below should cater for your needs. Simply replace `test.exe` with your executable name of choice. Note that that `Pattern` contains a regular expression so the `$` sign and the `.` are treated as regular expression control characters. Please refer to PR #108 for further details.

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <!-- Test Framework Configuration -->
    <!-- <RunConfiguration /> -->
	
    <!-- Data Collection Configuration -->
    <!-- <DataCollectionRunSettings /> -->

    <!-- BoostTest Adapter Configuration -->
    <BoostTest>
        <!-- <ForceListContent>true</ForceListContent> -->
        <Filters>
            <Include>
                <Pattern>test.exe$</Pattern>
            </Include>
        </Filters>
    </BoostTest>		
</RunSettings>
```

**Comment by guwirth** [comment]
:+1:

**Pull request merged**
