### PR TITLE
Making the repo build out-of-the-box 

### PR DESCRIPTION
**Pull request by mwu-tow**
Hi,
Due to a few issues the solution does not properly build after cloning a repo. I have done following changes to fix this:
* I have removed the current contents from packages directory — it wasn't complete and it disoriented nuget. Nuget automatically will restore packages and populate the packages directory, there's no point in keeping these files under version control.
* I have added NCalc dependency to the `BoostTestAdapter/packages.config` — so the Nuget automatically downloads that dependency
* I have added `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll` (from the VS 2012 installation) to the version control. Thanks to that having VS 2012 installed is not necessary to develop the test adapter.

With changes listed above, now I'm able build and run the test adapter right after cloning the repository. Only the NUnit test project fails but it is caused by issue #5.
Please let me know if these changes work for you. I don't have much experience with C# projects, so there might a better way to achieve the goals — I will happily accept any guidance.

### CODE REVIEW

**Comment by netspiri** [comment]
@mwu-tow many thanks for highlighting this issue and contributing towards BUTA. The issue reported here is due to an oversight from side where I failed to recognize that Git did not upload a number of dependencies due to my local global git ignore.

With respect to [this commit](https://github.com/mwu-tow/vs-boost-unit-test-adapter/commit/81a81027848aa3941268912b8c20f48c25b2a967) I do not think that can be accepted because we found nowhere that Microsoft.VisualStudio.TestPlatform.ObjectModel.dll can be redistributed.

**Comment by mwu-tow** [comment]
Thank you for the reply.

As for the `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll` — I believe you are redistributing it anyway, as it is being copied into the VSIX package.  
I know that some other VS plugins have this file on github but I understand that it is hardly a legal argument. 

If you wish I could submit a pull request without the said commit?

**Comment by netspiri** [comment]
@mwu-tow we tested your commit and after updating Nuget on our local machines, the package restore functionality seems of Nuget to be doing its job.  With the version I had, I did not have the possibility to manage NCalc via Nuget.

We have the option to either upload the missing libraries that were omitted by Git by mistake or go with the way you are suggesting.  I think I do like your approach better, so please submit a pull request without [this commit](https://github.com/mwu-tow/vs-boost-unit-test-adapter/commit/81a81027848aa3941268912b8c20f48c25b2a967).

With respect to _Microsoft.VisualStudio.TestPlatform.ObjectModel.dll_ we prefer not to have it included along with the sources.

**Comment by mwu-tow** [comment]
Done. The problematic commit is no longer a part of this pull request.

**Pull request merged**
